import { Dancing_Script } from "next/font/google";
import localFont from "next/font/local";
// import PortfolioBot from "../../chatbot/PortfolioBot";
import "../globals.css";
import Navbar from "../../components/portfolio/Navbar";
import Footer from "../../components/portfolio/Footer";
import WhattsAppShare from "../../whatts-app-share/WhattsAppShare";


// google fonts
const dancing_script = Dancing_Script({
  subsets: ["latin", "latin-ext", "vietnamese"],
  weight: ["400", "500", "600", "700"],
  variable: "--${string}",
});

// Load local fonts
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
export const metadata = {
  title: "The Bee Blessing | Portfolio",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${dancing_script}`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
        {/* <PortfolioBot /> */}
        <WhattsAppShare/>
      </body>
    </html>
  );
}
