import localFont from "next/font/local";
import "../globals.css";
import ENavbar from '../../components/ecommerce/ENavbar'
import EFooter from '../../components/ecommerce/EFooter'
import WhattsAppShare from '../../whatts-app-share/WhattsAppShare'



const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "The Bee Blessing | E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ENavbar/>
        <main>{children}</main>
        <WhattsAppShare/>
        <EFooter/>
      </body>
    </html>
  );
}
